### ISSUE TITLE
Orb of Servitude duplication 

### ISSUE THREAD

**Issue by mihkee** [slicedlime/Sacrifice#2]
Sacrificing too many items of the requested item rewards the player infinitly. 
Version - Beta 0.4
the current sacrifice was 2 string 
https://www.youtube.com/watch?v=jVgvI-788CU

**Comment by slicedlime** [comment]
Yikes - thanks, will look at that asap.

**Comment by NarcolepticFrog** [comment]
Thanks for fixing this :) I ran into it this evening and was just getting ready to post a bug report.
