### ISSUE TITLE
When the difficulty reaches 10,000, the game may fail to determain the next sacrifice

### ISSUE THREAD

**Issue by NeunEinser** [slicedlime/Sacrifice#4]
10,000 is not arbitary, it is the value where the game can only choose a totem of undying by definition (All other items would require an amount of more than 5 at this point). Most of the times, the function `newgoal.mcfunction` does run more commands than the max chain length, which is set to 100,000 after installation of the datapack. Sometimes it does actually succeed, though.
When setting `maxCommandChainLength` to 1,000,000, a huge lagspike occurs and while the end of the function is reached (Debug `say` at the end of it gets executed), no item is chosen.
Possibly an edge case when the list of possible items has a length of 1.

**Comment by slicedlime** [comment]
This happens on day 27, in the current difficulty scaling. I think the reasonable thing to do might be to just start scaling up the number of max items when the value starts getting very high.
